export type { default as Artista } from './artista';
export type { default as ArtigoJornal } from './artigo-jornal';
export { default as Data } from './data';
export type { default as Especialidade } from './especialidade';
export type { default as Exposicao } from './exposicao';
export { default as Fato } from './fato';
export type { default as Obra } from './obra';
export type { default as Pessoa } from './pessoa';
export type { default as Profissao } from './profissao';
export type { default as PoliticaPublica } from './politicapublica';
export { default as TipoCapital } from './tipo_capital';
export type { default as TrocaCapital } from './troca_capital';
export type { default as DependencyWheel } from './dependency-wheel';
export type { default as Livro } from './livro';
export type { default as Prefeito } from './prefeito';
